routes/web.php
<?php

use App\Http\Controllers\ReceiptController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\StatusController;


Route::group(['middleware' => ['get.menu', 'check.auth']], function () {
    Route::get('/', function () { return view('auth.login'); });

    Auth::routes();

    Route::resource('receipts', 'ReceiptController');   //create receipts resource
    Route::get('receipt/{id}/print', [ReceiptController::class, 'printReceipt'])->name('receipt-print');
    Route::resource('customers',  'CustomerController');   //create customers resource
    Route::get('receipt/archived', [ReceiptController::class, 'archivedList'])->name('receipt.archived');
    Route::get('receipt/{id}/archived', [ReceiptController::class, 'archived'])->name('receipt.fileAway');

    Route::get('/edit/password/{id}', [UsersController::class, 'editPassword'])->name('edit.password');
    Route::post('/update/password/{id}', [UsersController::class, 'updatePassword'])->name('update.password');
    Route::resource('users','UsersController');

    Route::get('profile', [ProfileController::class, 'edit'])->name('edit.profile');
    Route::post('profile',[ProfileController::class, 'update'])->name('update.profile');

    Route::resource('roles','RolesController');

});

Route::group(['middleware' => ['check.auth']], function () {

    Route::prefix('master')->group(function () {
        Route::get('/users', function () {
            // Matches The "/admin/users" URL
        });

        Route::get('status', [StatusController::class, 'index'])->name('status.index');
        Route::get('status/create', [StatusController::class, 'create'])->name('status.create');
        Route::post('status', [StatusController::class, 'store'])->name('status.store');
        Route::get('status/{id}/edit', [StatusController::class, 'edit'])->name('status.edit');
        Route::put('status/{id}', [StatusController::class, 'update'])->name('status.update');

        Route::get('profile', [ProfileController::class, 'edit'])->name('edit.profile');
        Route::post('profile',[ProfileController::class, 'update'])->name('update.profile');

        Route::get('/roles/move/move-up',      'RolesController@moveUp')->name('roles.up');
        Route::get('/roles/move/move-down',    'RolesController@moveDown')->name('roles.down');

        Route::prefix('menu/element')->group(function () {
            Route::get('/',             'MenuElementController@index')->name('menu.index');
            Route::get('/move-up',      'MenuElementController@moveUp')->name('menu.up');
            Route::get('/move-down',    'MenuElementController@moveDown')->name('menu.down');
            Route::get('/create',       'MenuElementController@create')->name('menu.create');
            Route::post('/store',       'MenuElementController@store')->name('menu.store');
            Route::get('/get-parents',  'MenuElementController@getParents');
            Route::get('/edit',         'MenuElementController@edit')->name('menu.edit');
            Route::post('/update',      'MenuElementController@update')->name('menu.update');
            Route::get('/show',         'MenuElementController@show')->name('menu.show');
            Route::get('/delete',       'MenuElementController@delete')->name('menu.delete');
        });

        Route::get('/breadcrumb', function(){   return view('dashboard.base.breadcrumb'); });
        Route::get('/cards', function(){        return view('dashboard.base.cards'); });
        Route::get('/carousel', function(){     return view('dashboard.base.carousel'); });
        Route::get('/collapse', function(){     return view('dashboard.base.collapse'); });

        Route::get('/jumbotron', function(){    return view('dashboard.base.jumbotron'); });
        Route::get('/list-group', function(){   return view('dashboard.base.list-group'); });
        Route::get('/navs', function(){         return view('dashboard.base.navs'); });
        Route::get('/pagination', function(){   return view('dashboard.base.pagination'); });

        Route::get('/popovers', function(){     return view('dashboard.base.popovers'); });
        Route::get('/progress', function(){     return view('dashboard.base.progress'); });
        Route::get('/scrollspy', function(){    return view('dashboard.base.scrollspy'); });
        Route::get('/switches', function(){     return view('dashboard.base.switches'); });

        Route::get('/tabs', function () {       return view('dashboard.base.tabs'); });
        Route::get('/tooltips', function () {   return view('dashboard.base.tooltips'); });

        Route::get('/charts', function () {     return view('dashboard.charts'); });
        Route::get('/widgets', function () {    return view('dashboard.widgets'); });
        Route::get('/google-maps', function(){  return view('dashboard.googlemaps'); });
        Route::get('/404', function () {        return view('dashboard.404'); });
        Route::get('/500', function () {        return view('dashboard.500'); });
        Route::prefix('buttons')->group(function () {
            Route::get('/buttons', function(){          return view('dashboard.buttons.buttons'); });
            Route::get('/button-group', function(){     return view('dashboard.buttons.button-group'); });
            Route::get('/dropdowns', function(){        return view('dashboard.buttons.dropdowns'); });
            Route::get('/brand-buttons', function(){    return view('dashboard.buttons.brand-buttons'); });
            Route::get('/loading-buttons', function(){  return view('dashboard.buttons.loading-buttons'); });
        });
        Route::prefix('editors')->group(function () {
            Route::get('/code-editor', function(){          return view('dashboard.editors.code-editor'); });
            Route::get('/markdown-editor', function(){      return view('dashboard.editors.markdown-editor'); });
            Route::get('/text-editor', function(){          return view('dashboard.editors.text-editor'); });
        });

        Route::prefix('icon')->group(function () {  // word: "icons" - not working as part of adress
            Route::get('/coreui-icons', function(){         return view('dashboard.icons.coreui-icons'); });
            Route::get('/flags', function(){                return view('dashboard.icons.flags'); });
            Route::get('/brands', function(){               return view('dashboard.icons.brands'); });
        });

        Route::prefix('notifications')->group(function () {
            Route::get('/alerts', function(){               return view('dashboard.notifications.alerts'); });
            Route::get('/badge', function(){                return view('dashboard.notifications.badge'); });
            Route::get('/modals', function(){               return view('dashboard.notifications.modals'); });
            Route::get('/toastr', function(){               return view('dashboard.notifications.toastr'); });
        });
        Route::prefix('plugins')->group(function () {
            Route::get('/calendar', function(){             return view('dashboard.plugins.calendar'); });
            Route::get('/draggable-cards', function(){      return view('dashboard.plugins.draggable-cards'); });
            Route::get('/spinners', function(){             return view('dashboard.plugins.spinners'); });
        });

        Route::prefix('tables')->group(function () {
            Route::get('/', function () {             return view('dashboard.tables.tables'); });
            Route::get('/datatables', function () {         return view('dashboard.tables.datatables'); });
        });

        Route::prefix('apps')->group(function () {
            Route::prefix('invoicing')->group(function () {
                Route::get('/invoice', function () {        return view('dashboard.apps.invoicing.invoice'); });
            });
        });

        Route::prefix('email')->group(function () {
            Route::get('/inbox', function () {          return view('dashboard.apps.email.inbox'); });
            Route::get('/message', function () {        return view('dashboard.apps.email.message'); });
            Route::get('/compose', function () {        return view('dashboard.apps.email.compose'); });
        });

        Route::resource('notes', 'NotesController');
    });

});

/*Route::get('locale', 'LocaleController@locale');*/

resources/views/dashboard/shared/breadcrumb.blade.php
        <!-- Breadcrumb-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <?php $segments = ''; ?>
            @for($i = 1; $i <= count(Request::segments()); $i++)
                <?php $segments .= '/'. Request::segment($i); ?>
                @if($i < count(Request::segments()))
                    <li class="breadcrumb-item">{{ Request::segment($i) }}</li>
                @else
                    <li class="breadcrumb-item active">{{ Request::segment($i) }}</li>
                @endif
            @endfor
          <!-- Breadcrumb Menu-->
          <li class="breadcrumb-menu d-md-down-none">
            <div class="btn-group" role="group" aria-label="Button group">
              <a class="btn" href="#">
                <i class="icon-speech"></i>
              </a>
              <a class="btn" href="./">
                <i class="icon-graph"></i>  Dashboard</a>
              <a class="btn" href="#">
                <i class="icon-settings"></i>  Settings</a>
            </div>
          </li>
        </ol>

resources/views/dashboard/shared/footer.blade.php
<footer class="c-footer">
    <div><a href="#">AWimport</a> &copy; <?php echo date('Y');?> creativeLabs. </div>
    {{--<div class="ml-auto">&nbsp;<a href="#">AWimport Admin .</a></div>--}}
</footer>

resources/views/dashboard/shared/header.blade.php
<div class="c-wrapper">
    <header class="c-header c-header-light c-header-fixed c-header-with-subheader">
        <button class="c-header-toggler c-class-toggler d-lg-none mr-auto" type="button" data-target="#sidebar" data-class="c-sidebar-show"><span class="c-header-toggler-icon"></span></button><a class="c-header-brand d-sm-none" href="#"><img class="c-header-brand" src="{{asset('assets/brand/awimport_logo.svg')}}" width="97" height="46" alt="CoreUI Logo"></a>
        <button class="c-header-toggler c-class-toggler ml-3 d-md-down-none" type="button" data-target="#sidebar" data-class="c-sidebar-lg-show" responsive="true"><span class="c-header-toggler-icon"></span></button>
        <?php
        use App\MenuBuilder\FreelyPositionedMenus;
        if(isset($appMenus['top menu'])){
            FreelyPositionedMenus::render( $appMenus['top menu'] , 'c-header-', 'd-md-down-none');
        }
        ?>
        <ul class="c-header-nav ml-auto mr-4">
            <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link">
                    <svg class="c-icon">
                        <use xlink:href="{{ asset('icons/sprites/free.svg#cil-bell') }}"></use>
                    </svg></a></li>
            <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link">
                    <svg class="c-icon">
                        <use xlink:href="{{ asset('icons/sprites/free.svg#cil-list-rich') }}"></use>
                    </svg></a></li>
            <li class="c-header-nav-item d-md-down-none mx-2">
                <a class="c-header-nav-link">
                    <svg class="c-icon">
                        <use xlink:href="{{ asset('icons/sprites/free.svg#cil-envelope-open') }}"></use>
                    </svg>
                </a>
            </li>
            <li class="c-header-nav-item d-md-down-none mx-2">
                {{Auth::user()->name}}
            </li>
            <li class="c-header-nav-item dropdown"><a class="c-header-nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    <div class="c-avatar"><img class="c-avatar-img" src="{{Auth::user()->avatar}}" alt="{{Auth::user()->email}}"></div>
                </a>
                <div class="dropdown-menu dropdown-menu-right pt-0">
                    <div class="dropdown-header bg-light py-2">
                        <strong>{{Auth::user()->name}}</strong>
                    </div>
                    {{--<div class="dropdown-header bg-light py-2">
                        <strong>Account</strong>
                    </div>
                    <a class="dropdown-item" href="#">
                        <svg class="c-icon mr-2">
                            <use xlink:href="{{ asset('icons/sprites/free.svg#cil-bell') }}"></use>
                        </svg> Updates<span class="badge badge-info ml-auto">42</span></a><a class="dropdown-item" href="#">
                        <svg class="c-icon mr-2">
                            <use xlink:href="{{ asset('icons/sprites/free.svg#cil-envelope-open') }}"></use>
                        </svg> Messages<span class="badge badge-success ml-auto">42</span></a><a class="dropdown-item" href="#">
                        <svg class="c-icon mr-2">
                            <use xlink:href="{{ asset('icons/sprites/free.svg#cil-task') }}"></use>
                        </svg> Tasks<span class="badge badge-danger ml-auto">42</span></a><a class="dropdown-item" href="#">
                        <svg class="c-icon mr-2">
                            <use xlink:href="{{ asset('icons/sprites/free.svg#cil-comment-square')}}"></use>
                        </svg> Comments<span class="badge badge-warning ml-auto">42</span>
                    </a>--}}
                    <div class="dropdown-header bg-light py-2">
                        <strong>Ajustes</strong>
                    </div>
                    {{--<a class="dropdown-item" href="{{ route('edit.profile') }}">
                        <svg class="c-icon mr-2">
                            <use xlink:href="{{ asset('icons/sprites/free.svg#cil-user')}}"></use>
                        </svg> Perfil
                    </a>--}}
                    {{--<a class="dropdown-item" href="#">
                        <svg class="c-icon mr-2">
                            <use xlink:href="{{ asset('icons/sprites/free.svg#cil-settings') }}"></use>
                        </svg> Settings</a><a class="dropdown-item" href="#">
                        <svg class="c-icon mr-2">
                            <use xlink:href="{{ asset('icons/sprites/free.svg#cil-credit-card') }}"></use>
                        </svg> Payments<span class="badge badge-secondary ml-auto">42</span></a><a class="dropdown-item" href="#">
                        <svg class="c-icon mr-2">
                            <use xlink:href="{{ asset('icons/sprites/free.svg#cil-file') }}"></use>
                        </svg> Projects<span class="badge badge-primary ml-auto">42</span>
                    </a>--}}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <svg class="c-icon mr-2">
                            <use xlink:href="{{ asset('icons/sprites/free.svg#cil-account-logout')}}"></use>
                        </svg><form action="/logout" method="POST"> @csrf <button type="submit" class="btn btn-ghost-dark btn-block">Salir</button></form>
                    </a>
                </div>
            </li>
        </ul>
        {{--<div class="c-subheader px-3">
            <ol class="breadcrumb border-0 m-0">
                <li class="breadcrumb-item"><a href="{{ route('receipts.index') }}">Home</a></li>
                <?php $segments = ''; ?>
                @for($i = 1; $i <= count(Request::segments()); $i++)
                    <?php $segments .= '/'. Request::segment($i); ?>
                    @if($i < count(Request::segments()))
                        <li class="breadcrumb-item">{{ Request::segment($i) }}</li>
                    @else
                        <li class="breadcrumb-item active">{{ Request::segment($i) }}</li>
                    @endif
                @endfor
            </ol>
        </div>--}}
    </header>

resources/views/dashboard/shared/nav-builder.blade.php
<?php
/*
    $data = $menuel['elements']
*/

if(!function_exists('renderDropdown')){
    function renderDropdown($data){
        if(array_key_exists('slug', $data) && $data['slug'] === 'dropdown'){
            echo '<li class="c-sidebar-nav-dropdown">';
            echo '<a class="c-sidebar-nav-dropdown-toggle" href="#">';
            if($data['hasIcon'] === true && $data['iconType'] === 'coreui'){
                echo '<i class="' . $data['icon'] . ' c-sidebar-nav-icon"></i>';
            }
            echo $data['name'] . '</a>';
            echo '<ul class="c-sidebar-nav-dropdown-items">';
            renderDropdown( $data['elements'] );
            echo '</ul></li>';
        }else{
            for($i = 0; $i < count($data); $i++){
                if( $data[$i]['slug'] === 'link' ){
                    echo '<li class="c-sidebar-nav-item">';
                    echo '<a class="c-sidebar-nav-link" href="' . url($data[$i]['href']) . '">';
                    echo '<span class="c-sidebar-nav-icon"></span>' . $data[$i]['name'] . '</a></li>';
                }elseif( $data[$i]['slug'] === 'dropdown' ){
                    renderDropdown( $data[$i] );
                }
            }
        }
    }
}
?>

        <div class="c-sidebar-brand">
            <img class="c-sidebar-brand-full" src="{{asset('assets/brand/awimport_logo.svg')}}" width="118" height="46" alt="CoreUI Logo">
            <img class="c-sidebar-brand-minimized" src="{{asset('assets/brand/awimport_logo.svg')}}" width="118" height="46" alt="CoreUI Logo">
        </div>
        <ul class="c-sidebar-nav">
            <li class="c-sidebar-nav-dropdown">
                <a class="c-sidebar-nav-dropdown-toggle" href="#">
                    <i class="cil-calendar-check c-sidebar-nav-icon"></i>
                    Recibos
                </a>
                <ul class="c-sidebar-nav-dropdown-items">
                    <li class="c-sidebar-nav-item">
                        <a class="c-sidebar-nav-link" href="{{ route('receipts.index') }}">
                            <span class="c-sidebar-nav-icon"></span>
                            Ver Recibos
                        </a>
                    </li>
                    <li class="c-sidebar-nav-item">
                        <a class="c-sidebar-nav-link" href="{{ route('receipts.create') }}">
                            <span class="c-sidebar-nav-icon"></span>
                            Crear Recibo
                        </a>
                    </li>
                    <li class="c-sidebar-nav-item">
                        <a class="c-sidebar-nav-link" href="{{ route('receipt.archived') }}">
                            <span class="c-sidebar-nav-icon"></span>
                            Archivo
                        </a>
                    </li>
                </ul>
            </li>
            <li class="c-sidebar-nav-dropdown">
                <a class="c-sidebar-nav-dropdown-toggle" href="#">
                    <i class="cil-contact c-sidebar-nav-icon"></i>
                    Clientes
                </a>
                <ul class="c-sidebar-nav-dropdown-items">
                    <li class="c-sidebar-nav-item">
                        <a class="c-sidebar-nav-link" href="{{ route('customers.index') }}">
                            <span class="c-sidebar-nav-icon"></span>
                            Ver clientes
                        </a>
                    </li>
                    <li class="c-sidebar-nav-item">
                        <a class="c-sidebar-nav-link" href="{{ route('customers.create') }}">
                            <span class="c-sidebar-nav-icon"></span>
                            Agregar cliente
                        </a>
                    </li>
                </ul>
            </li>
            <li class="c-sidebar-nav-dropdown">
                <a class="c-sidebar-nav-dropdown-toggle" href="#">
                    <i class="cil-settings c-sidebar-nav-icon"></i>
                    Configuración
                </a>
                <ul class="c-sidebar-nav-dropdown-items">
                    <li class="c-sidebar-nav-item">
                        <a class="c-sidebar-nav-link" href="{{ route('users.index') }}">
                            <span class="c-sidebar-nav-icon"></span>
                            Usuarios
                        </a>
                    </li>
                    <li class="c-sidebar-nav-item">
                        <a class="c-sidebar-nav-link" href="{{ route('users.create') }}">
                            <span class="c-sidebar-nav-icon"></span>
                            Agregar Usuario
                        </a>
                    </li>
                    <li class="c-sidebar-nav-item">
                        <a class="c-sidebar-nav-link" href="{{ route('roles.index') }}">
                            <span class="c-sidebar-nav-icon"></span>
                            Roles
                        </a>
                    </li>
                </ul>
            </li>
        {{--@if(isset($appMenus['sidebar menu']))
            @foreach($appMenus['sidebar menu'] as $menuel)
                @if($menuel['slug'] === 'link')
                    <li class="c-sidebar-nav-item">
                        <a class="c-sidebar-nav-link" href="{{ url($menuel['href']) }}">
                        @if($menuel['hasIcon'] === true)
                            @if($menuel['iconType'] === 'coreui')
                                <i class="{{ $menuel['icon'] }} c-sidebar-nav-icon"></i>
                            @endif
                        @endif
                        {{ $menuel['name'] }}
                        </a>
                    </li>
                @elseif($menuel['slug'] === 'dropdown')
                    <?php renderDropdown($menuel) ?>
                @elseif($menuel['slug'] === 'title')
                    <li class="c-sidebar-nav-title">
                        @if($menuel['hasIcon'] === true)
                            @if($menuel['iconType'] === 'coreui')
                                <i class="{{ $menuel['icon'] }} c-sidebar-nav-icon"></i>
                            @endif
                        @endif
                        {{ $menuel['name'] }}
                    </li>
                @endif
            @endforeach
        @endif--}}
        </ul>
        {{--<button class="c-sidebar-minimizer c-class-toggler" type="button" data-target="_parent" data-class="c-sidebar-unfoldable"></button>--}}
    </div>

resources/views/dashboard/shared/universal-info.blade.php
@extends('dashboard.base')

@section('content')


<div class="container-fluid">
  <div class="fade-in">
    <div class="row">
      <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                @if(Session::has('title'))
                <h4>{{ Session::get('title') }}</h4>
                @endif
            </div>
            <div class="card-body">

                @if(Session::has('message'))
                    <div class="alert alert-success" role="alert">{{ Session::get('message') }}</div>
                @else
                    <div class="alert alert-success" role="alert">Success</div>
                @endif
                
                @if(Session::has('back'))
                    @if(Session::has('backParams'))
                        <a href="{{ route( Session::get('back'), Session::get('backParams') ) }}" class="btn btn-lg btn-primary">Return</a>
                    @else
                        <a href="{{ route( Session::get('back') ) }}" class="btn btn-lg btn-primary">Return</a>
                    @endif
                @endif

            </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

@section('javascript')


@endsection